filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log
    - /var/log/apache/access.log
    - /var/log/apache/error.log
    - /var/log/app/*.log

#output.console:
#  enabled: true

output.elasticsearch:
  enabled: true
  hosts: ["host.docker.internal:9200"]
  username: "elastic"
  password: "changeme"
  indices:
  - index: "nginx-%{+yyyy.MM.dd}"
    when.equals:
      event.module: "nginx"
  - index: "apache-%{+yyyy.MM.dd}"
    when.equals:
      event.module: "apache"
  #index: "nginx-%{+yyyy.MM.dd}"

filebeat.modules:
- module: nginx
  access:
    enabled: true
    var.paths: ["/var/log/nginx/access.log"]
  error:
    enabled: true
    var.paths: ["/var/log/nginx/error.log"]

- module: apache
  access:
    enabled: true
    var.paths: ["/var/log/apache/access.log"]
  error:
    enabled: true
    var.paths: ["/var/log/apache/error.log"]
