version: '3.2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    #deploy:
    #  resources:
    #    limits:
    #      cpus: 0.50
    #      memory: 1G

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.2
    container_name: filebeat
    depends_on:
      - elasticsearch
    restart: unless-stopped
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - nginx_log:/var/log/nginx:ro
      - apache_log:/var/log/apache:ro
      - rabbit_log:/var/log/rabbitmq:ro
      - celery_log:/var/log/celery:ro
      - mysql_log:/var/log/mysql:ro
      - echidna_log:/var/log/echidna:ro
    command: ["filebeat", "-e", "-strict.perms=false"]
    #deploy:
    #  resources:
    #    limits:
    #      memory: 500M

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    depends_on:
      - elasticsearch
    restart: unless-stopped
    ports:
      - 5601:5601
    links:
      - elasticsearch
    #deploy:
    #  resources:
    #    limits:
    #      memory: 1G

  mysql:
    image: mysql:8.0.28
    container_name: mysql
    depends_on:
      - filebeat
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: "echidna"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
      - mysql_log:/var/log/mysql
    ports:
      - "3306:3306"
    #deploy:
    #  resources:
    #    limits:
    #      memory: 1G

  mongo:
    image: mongo:5.0.6
    container_name: mongo
    depends_on:
      - filebeat
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: echidna
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    ports:
      - "27017:27017"
    #deploy:
    #  resources:
    #    limits:
    #      memory: 1G

  redis:
    image: bitnami/redis:6.2.6
    container_name: redis
    depends_on:
      - filebeat
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    #deploy:
    #  resources:
    #    limits:
    #      memory: 500M

  rabbit:
    image: rabbitmq:3.9.13-management
    container_name: rabbit
    depends_on:
      - mysql
      - mongo
      - redis
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_LOG_BASE: /var/log/rabbitmq/
      RABBITMQ_LOGS: rabbit.log
    volumes:
      - rabbit_data:/var/lib/rabbitmq
      - rabbit_log:/var/log/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    #deploy:
    #  resources:
    #    limits:
    #      memory: 1G

  celery:
    image: echidna
    container_name: celery
    depends_on:
      - rabbit
    restart: always
    volumes:
    - celery_log:/var/log/celery
    - echidna_log:/var/log/echidna
    ports:
    - "8082:80"
    #deploy:
    #  resources:
    #    limits:
    #      memory: 500M

  flower:
    image: mher/flower:0.9.7
    container_name: flower
    depends_on:
      - celery
    working_dir: /data
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@host.docker.internal:5672//
      CELERY_RESULT_BACKEND: redis://host.docker.internal:6379/0
    #deploy:
    #  resources:
    #    limits:
    #      memory: 500M

  echidna:
    image: echidna
    container_name: echidna
    depends_on:
      - celery
    restart: always
    volumes:
    - apache_log:/var/log/apache2
    - echidna_log:/var/log/echidna
    ports:
    - "8081:80"
    #deploy:
    #  resources:
    #    limits:
    #      memory: 1G

  nginx:
    image: nginx:1.21.6
    container_name: nginx
    depends_on:
      - echidna
    restart: always
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
    ports:
    - "80:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - nginx_log:/var/log/nginx
    #deploy:
    #  resources:
    #    limits:
    #      memory: 500M

  #postgres:
  #  image: postgres:13.3
  #  container_name: postgres
  #  restart: always
  #  environment:
  #    POSTGRES_DB: "postgres"
  #    POSTGRES_USER: "postgres"
  #    POSTGRES_PASSWORD: "postgres"
  #  volumes:
  #    - postgres_data:/var/lib/postgresql/data
  #    - postgres_log:/var/log/postgresql
  #  ports:
  #    - "5432:5432"
  #  command: ["postgres", "-c", "logging_collector=on", "-c", "log_directory=/var/log/postgresql/", "-c", "log_statement=all"]

  #pgadmin:
  #  image: dpage/pgadmin4
  #  container_name: pgadmin
  #  restart: always
  #  depends_on:
  #    - postgres
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #    PGADMIN_DEFAULT_PASSWORD: admin
  #  volumes:
  #    - pgadmin_data:/var/lib/pgadmin
  #  ports:
  #    - "5555:80"

volumes:
  mysql_data:
  rabbit_data:
  elasticsearch_data:
  nginx_log:
  apache_log:
  celery_log:
  rabbit_log:
  mysql_log:
  echidna_log:
  mongo_data:
  mongo_config:
