version: '3.2'
services:

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.2
    container_name: filebeat
    restart: unless-stopped
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - nginx_log:/var/log/nginx:ro
      - apache_log:/var/log/apache:ro
      - rabbit_log:/var/log/rabbitmq:ro
      - celery_log:/var/log/celery:ro
      - mysql_log:/var/log/mysql:ro
      - echidna_log:/var/log/echidna:ro
    depends_on:
      - nginx
      - echidna
      - celery
      - mysql
      - rabbit
      - elasticsearch
    command: ["filebeat", "-e", "-strict.perms=false"]
    

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.001'
    #      memory: 2G

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    restart: unless-stopped
    ports:
      - 5601:5601
    #environment:
    #  ELASTICSEARCH_URL: http://host.docker.internal:9200
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  nginx:
    image: nginx:1.21.6
    container_name: nginx
    restart: always
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
    ports:
    - "80:80"
    depends_on:
      - echidna
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - nginx_log:/var/log/nginx

  echidna:
    image: echidna
    container_name: echidna
    restart: always
    volumes:
    - apache_log:/var/log/apache2
    - echidna_log:/var/log/echidna
    ports:
    - "8081:80"
    depends_on:
      - celery

  celery:
    image: echidna
    container_name: celery
    restart: always
    volumes:
    - celery_log:/var/log/celery
    ports:
    - "8082:80"
    depends_on:
      - rabbit
      - redis

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_LOG_BASE: /var/log/rabbitmq/
      RABBITMQ_LOGS: rabbit.log
    volumes:
      - rabbit_data:/var/lib/rabbitmq
      - rabbit_log:/var/log/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  #postgres:
  #  image: postgres:13.3
  #  container_name: postgres
  #  restart: always
  #  environment:
  #    POSTGRES_DB: "postgres"
  #    POSTGRES_USER: "postgres"
  #    POSTGRES_PASSWORD: "postgres"
  #  volumes:
  #    - postgres_data:/var/lib/postgresql/data
  #    - postgres_log:/var/log/postgresql
  #  ports:
  #    - "5432:5432"
  #  command: ["postgres", "-c", "logging_collector=on", "-c", "log_directory=/var/log/postgresql/", "-c", "log_statement=all"]

  #pgadmin:
  #  image: dpage/pgadmin4
  #  container_name: pgadmin
  #  restart: always
  #  depends_on:
  #    - postgres
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #    PGADMIN_DEFAULT_PASSWORD: admin
  #  volumes:
  #    - pgadmin_data:/var/lib/pgadmin
  #  ports:
  #    - "5555:80"

  redis:
    image: bitnami/redis
    container_name: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0.28
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: "echidna"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
      - mysql_log:/var/log/mysql
    ports:
      - "3306:3306"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: echidna
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    ports:
      - "27017:27017"
volumes:
  mysql_data:
  rabbit_data:
  elasticsearch_data:
  nginx_log:
  apache_log:
  celery_log:
  rabbit_log:
  mysql_log:
  echidna_log:
  mongo_data:
  mongo_config:
