FROM nginx:latest
#RUN ln -s /dev/stdout /var/log/nginx/access.log
#RUN ln -s /dev/stderr /var/log/nginx/error.log
RUN rm /var/log/nginx/access.log
RUN rm /var/log/nginx/error.log

#\\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes\project2_nginx_log\_data
